spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_api
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: "7f8b4cd28b7857"
    password: "a25f1028b54e69"


