CREATE TABLE users
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             varchar(255),
    first_name        varchar(255),
    password          varchar(255),
    role              varchar(255),
    verification_code varchar(255),
    primary key (id)
)