CREATE TABLE news(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(255),
    description varchar(255),
    language varchar(255),
    publication_date date,
    title varchar(255),
    author_id integer,
    primary key (id)
);